name: CI build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - uses: skjolber/maven-cache-github-action@v1
      with:
        step: restore
    - run: ./gradlew --no-daemon clean downloadAll build check test
    - uses: skjolber/maven-cache-github-action@v1
      with:
        step: save
